---
abstract: 'Ultra cheap profiling for use in production environments'
author:
  - 'Josh Jore <jjore@cpan.org>'
build_requires:
  ExtUtils::CBuilder: 0
  perl: v5.10.0
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200000, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-ContinuousProfiler
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Devel-ContinuousProfiler
  homepage: http://search.cpan.org/dist/Devel-ContinuousProfiler
  repository: git://github.com/jbenjore/Devel-ContinuousProfiler.git
version: 0.11
